### PR TITLE
Schedule rule deletes when signoffs are required (fixes #115)

### LINKED ISSUE #115: delete button should schedule deletion when signoffs are required on rules page
Right now, it tries to directly delete, which fails.

### PR DESCRIPTION
**Pull request by mozbhearsum**
This works, but needs an extra fix to make `rowHeight` get recalculated. I dug into that part a bit, and it turns out that the `List` we use has a `recomputeRowHeights` function to do just that. I tried to get that working with a `ref` (as suggested in https://github.com/bvaughn/react-virtualized/issues/545), but our architecture doesn't seem to allow it - I get an error about needing to use a `ForwardRef` instead, which I wasn't able to get working.

Before I dive deeper down that rabbit hole, is that the right way to go, or is there a better solution here?

### CODE REVIEW

**Comment by helfi92** [comment]
Changing the `key` of any React component will force the the component to be re-rendered. Would this fix the issue?

**Comment by mozbhearsum** [comment]
> Changing the `key` of any React component will force the the component to be re-rendered. Would this fix the issue?

It doesn't look like that works here. I tried changing the RuleCard's key:
```
         <RuleCard
           className={classes.ruleCard}
-          key={rule.rule_id}
+          key={`${rule.rule_id}-${rule.scheduledChange ? rule.scheduledChange.sc_id : ''}`}
           rule={rule}
           onRuleDelete={handleRuleDelete}
           onSignoff={() => handleSignoff(rule)}
           onRevoke={() => handleRevoke(rule)}
         />
```

...but it doesn't cause the row height to be recalculated. I'm guessing this is because the `List` is what calls `getRowHeight`, and it has its own key that is ultimately set by https://github.com/bvaughn/react-virtualized/blob/master/source/Grid/defaultCellRangeRenderer.js#L58.

**Comment by helfi92** [comment]
We use `VariableSizeList` to render the react-virtualized component. Did you try changing the key of`VariableSizeList`? Perhaps setting it to have `key={filteredRulesCount}`. My understanding is that it will force whatever is inside `VariableSizeList` to be re-created.

https://github.com/mozilla-frontend-infra/balrog-ui/blob/3de4510dccccaadb9a41519a715294840fbb30dd/src/views/Rules/ListRules/index.jsx#L696-L701

**Comment by mozbhearsum** [comment]
> We use VariableSizeList to render the react-virtualized component. Did you try changing the key ofVariableSizeList? Perhaps setting it to have key={filteredRulesCount}. My understanding is that it will force whatever is inside VariableSizeList to be re-created.

It didn't occur to me that I could just add a key to an object outside of a loop :upside_down_face:. What do you think about setting the key to the md5 hash of `filteredRulesWithScheduledChanges`? The alternative would be concat'ing all of the rule ids and sc ids together, I think.

**Comment by helfi92** [comment]
> What do you think about setting the key to the md5 hash of filteredRulesWithScheduledChanges?

In what circumstance will this hash change? Will deleting an item from filteredRulesWithScheduledChanges without re-fetching the list of rules make that value change?

**Comment by mozbhearsum** [comment]
> > What do you think about setting the key to the md5 hash of filteredRulesWithScheduledChanges?
> 
> In what circumstance will this hash change? Will deleting an item from filteredRulesWithScheduledChanges without re-fetching the list of rules make that value change?

As far as I know, this will change whenever `productChannelFilter` or `rulesWithScheduledChanges` changes (https://github.com/mozilla-frontend-infra/balrog-ui/blob/1f952b3fe80334babd3e6e5275cc37ad8d9329a0/src/views/Rules/ListRules/index.jsx#L303)

Besides first load, `rulesWithScheduledChanges` changes when:
* A delete is done or scheduled (https://github.com/mozilla-frontend-infra/balrog-ui/blob/1f952b3fe80334babd3e6e5275cc37ad8d9329a0/src/views/Rules/ListRules/index.jsx#L329)
* A signoff is made or revoked (https://github.com/mozilla-frontend-infra/balrog-ui/blob/1f952b3fe80334babd3e6e5275cc37ad8d9329a0/src/views/Rules/ListRules/index.jsx#L400, https://github.com/mozilla-frontend-infra/balrog-ui/blob/1f952b3fe80334babd3e6e5275cc37ad8d9329a0/src/views/Rules/ListRules/index.jsx#L470)

The height will always change when we schedule a deletion (because the scheduled changes section will now be shown), and has the potential to for signoff/revoke. The height will never change for a direct deletion, however (the card is simply removed, instead).

**Comment by helfi92** [comment]
Thanks for elaborating. Makes sense to me. Let's try going ahead with the md5 hash :)

**Comment by mozbhearsum** [comment]
> Thanks for elaborating. Makes sense to me. Let's try going ahead with the md5 hash :)

It's looking like this may not be a great option. The full rerender is a little sluggish (especially noticable when signing off or revoking a signoff), and it also causes a scroll all the way back to the top.

**Comment by helfi92** [comment]
> The full rerender is a little sluggish (especially noticable when signing off or revoking a signoff), and it also causes a scroll all the way back to the top.

Hm, in that case I think we could try the `ref` option. We might be able to use https://reactjs.org/docs/hooks-reference.html#useref to have a reference to the component.

**Comment by mozbhearsum** [comment]
This was pretty straightforward since we're already setting a ref on `VariableSizeList`.

File: src/views/Rules/ListRules/index.jsx [hunk 1]
```diff
@@ -707,6 +716,7 @@ function ListRules(props) {
                 scrollToRow={scrollToRow}
                 rowHeight={getRowHeight}
                 rowCount={filteredRulesCount}
+                listRef={ruleListRef}
```
Comment (helfi92) [inline src/views/Rules/ListRules/index.jsx]: Can this be renamed to `ref` instead of `listRef`? I _think_ `ref` is like `key` where the child component can't access that value and wont overwrite props.

```jsx
<ButtonComponent key={9999} />

function ButtonComponent(props) {
    console.log(props.key) // prints undefined
}
```

Comment (mozbhearsum) [reply src/views/Rules/ListRules/index.jsx]: Something like https://gist.github.com/mozbhearsum/3ed4f518e8c0d6e09ff3bc270ed31dca ?

I struggled a bit to make this work due to React things I don't quite understand. See https://github.com/facebook/flow/issues/7467, https://github.com/reactjs/rfcs/issues/103

Comment (helfi92) [reply src/views/Rules/ListRules/index.jsx]: > Something like https://gist.github.com/mozbhearsum/3ed4f518e8c0d6e09ff3bc270ed31dca

Yes! Exactly that. Maybe I can help a bit:

`useRef`:
* is a hook
* common use case is to access a child methods
* can also be used as an instance variable in a class but that has nothing to do with what we're trying to do

In our case, we use `useRef` to have access to methods from the List component of react-virtualized.

`useImperativeHandle`:
* is a hook
* customizes the instance value (`ref` value) that is exposed to the parent when the parent decides to use `useRef` to have access to the child methods
* `useImperativeHandle` should be used with `forwardRef`

In our case, we let `VariableSizeList` take care of interacting with the internals of react-virtualized and expose a method via `useImperativeHandle` to ListRules that it can use.

`forwardRef`:
* Allows you to forward a `ref` prop down the React tree. React won’t pass some props down (e.g., `key` and `ref`) since they are considered somewhat special. `forwardRef` will have React allow it:

```jsx
// React will pass `ref` as a second parameter
function Child(props, ref) {

}
```

In our case, we use `forwardRef` to attach a method to that ref via `useImperativeHandle`.

Comment (mozbhearsum) [reply src/views/Rules/ListRules/index.jsx]: Ah, so `forwardRef` is really just a flag to say "allow the ref to be passed"?

Thank you for the detailed explanation, this is very helpful.

**Comment by mozbhearsum** [comment]
I realize this drops `propTypes` and `defaultProps`, but I think that's unavoidable due to https://github.com/facebook/flow/issues/7467 (unless we switch to a class based component).

File: src/views/Rules/ListRules/index.jsx (hunk 1 above)
Comment (helfi92) [reply src/views/Rules/ListRules/index.jsx]: Correct. No problem :)

**Comment by helfi92** [comment]
> I realize this drops propTypes and defaultProps, but I think that's unavoidable due to facebook/flow#7467 (unless we switch to a class based component).

What happens when you try to add props? The linked issue has to do with prop-types not working with flow (fb static typing).

**Comment by mozbhearsum** [comment]
> > I realize this drops propTypes and defaultProps, but I think that's unavoidable due to [facebook/flow#7467](https://github.com/facebook/flow/issues/7467) (unless we switch to a class based component).
> 
> What happens when you try to add props? The linked issue has to do with prop-types not working with flow (fb static typing).

Things still work, but we get this error in the console:
`Warning: forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?`

**Comment by helfi92** [comment]
Hmm, I wonder if something like this would work:

```jsx
const WrappedComponent = React.forwardRef(
  function Component(props, ref) {
    return < ... />;
  }
);

WrappedComponent.propTypes = {
  // ...
};

WrappedComponent.defaultProps = {
  // ...
};
```

**Comment by mozbhearsum** [comment]
Looks like it!

**Comment by helfi92** [comment]
w00t! I will review soon :) Btw, WrappedComponent could just be `VariableSizeList` heh. Sorry for the confusion.

**Comment by mozbhearsum** [comment]
> w00t! I will review soon :) Btw, WrappedComponent could just be `VariableSizeList` heh. Sorry for the confusion.

Oh haha, of course.

**Comment by mozbhearsum** [comment]
Ah, I know what's up there. I'll fix it in a follow-up, thanks for the report!
